<?php

namespace App\Http\Requests\Fhir;

use App\Http\Requests\FhirRequest;
use App\Models\Fhir\Resources\Observation;
use Illuminate\Validation\Rule;

class ObservationRequest extends FhirRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array|string>
     */
    public function rules(): array
    {
        return array_merge(
            [
                'identifier' => 'nullable|array',
                'basedOn' => 'nullable|array',
                'partOf' => 'nullable|array',
                'status' => ['required', Rule::in(Observation::STATUS['binding']['valueset']['code'])],
                'category' => 'nullable|array',
                'code' => 'required|array',
                'subject' => 'required|array',
                'focus' => 'nullable|array',
                'encounter' => 'required|array',
                'effectiveDateTime' => 'nullable|date',
                'effectivePeriod' => 'nullable|array',
                'effectiveTiming' => 'nullable|array',
                'effectiveInstant' => 'nullable|date',
                'issued' => 'nullable|date',
                'performer' => 'nullable|array',
                'valueQuantity' => 'nullable|array',
                'valueCodeableConcept' => 'nullable|array',
                'valueString' => 'nullable|string',
                'valueBoolean' => 'nullable|boolean',
                'valueInteger' => 'nullable|integer',
                'valueRange' => 'nullable|array',
                'valueRatio' => 'nullable|array',
                'valueSampledData' => 'nullable|array',
                'valueTime' => 'nullable|date_format:H:i:s',
                'valueDateTime' => 'nullable|date',
                'valuePeriod' => 'nullable|array',
                'dataAbsentReason' => 'nullable|array',
                'interpretation' => 'nullable|array',
                'note' => 'nullable|array',
                'bodySite' => 'nullable|array',
                'method' => 'nullable|array',
                'specimen' => 'nullable|array',
                'device' => 'nullable|array',
                'referenceRange' => 'nullable|array',
                'referenceRange.*.low' => 'nullable|array',
                'referenceRange.*.high' => 'nullable|array',
                'referenceRange.*.type' => 'nullable|array',
                'referenceRange.*.appliesTo' => 'nullable|array',
                'referenceRange.*.age' => 'nullable|array',
                'referenceRange.*.text' => 'nullable|string',
                'hasMember' => 'nullable|array',
                'derivedFrom' => 'nullable|array',
                'component' => 'nullable|array',
                'component.*.code' => 'sometimes|array',
                'component.*.valueQuantity' => 'nullable|array',
                'component.*.valueCodeableConcept' => 'nullable|array',
                'component.*.valueString' => 'nullable|string',
                'component.*.valueBoolean' => 'nullable|boolean',
                'component.*.valueInteger' => 'nullable|integer',
                'component.*.valueRange' => 'nullable|array',
                'component.*.valueRatio' => 'nullable|array',
                'component.*.valueSampledData' => 'nullable|array',
                'component.*.valueTime' => 'nullable|date_format:H:i:s',
                'component.*.valueDateTime' => 'nullable|date',
                'component.*.valuePeriod' => 'nullable|array',
                'component.*.dataAbsentReason' => 'nullable|array',
                'component.*.interpretation' => 'nullable|array',
                'component.*.referenceRange' => 'nullable|array',
                'component.*.referenceRange.*.low' => 'nullable|array',
                'component.*.referenceRange.*.high' => 'nullable|array',
                'component.*.referenceRange.*.type' => 'nullable|array',
                'component.*.referenceRange.*.appliesTo' => 'nullable|array',
                'component.*.referenceRange.*.age' => 'nullable|array',
                'component.*.referenceRange.*.text' => 'nullable|string',
            ],
            $this->getIdentifierRules('identifier.*.'),
            $this->getReferenceRules('basedOn.*.'),
            $this->getReferenceRules('partOf.*.'),
            $this->getCodeableConceptRules('category.*.'),
            $this->getCodeableConceptRules('code.'),
            $this->getReferenceRules('subject.'),
            $this->getReferenceRules('focus.*.'),
            $this->getReferenceRules('encounter.'),
            $this->getPeriodRules('effectivePeriod.'),
            $this->getTimingRules('effectiveTiming.'),
            $this->getReferenceRules('performer.*.'),
            $this->getQuantityRules('valueQuantity.'),
            $this->getCodeableConceptRules('valueCodeableConcept.'),
            $this->getRangeRules('valueRange.'),
            $this->getRatioRules('valueRatio.'),
            $this->getSampledDataRules('valueSampledData.'),
            $this->getPeriodRules('valuePeriod.'),
            $this->getCodeableConceptRules('dataAbsentReason.'),
            $this->getCodeableConceptRules('interpretation.*.'),
            $this->getAnnotationRules('note.*.'),
            $this->getCodeableConceptRules('bodySite.'),
            $this->getCodeableConceptRules('method.'),
            $this->getReferenceRules('specimen.'),
            $this->getReferenceRules('device.'),
            $this->getSimpleQuantityRules('referenceRange.*.low.'),
            $this->getSimpleQuantityRules('referenceRange.*.high.'),
            $this->getCodeableConceptRules('referenceRange.*.type.'),
            $this->getCodeableConceptRules('referenceRange.*.appliesTo.'),
            $this->getRangeRules('referenceRange.*.age.'),
            $this->getReferenceRules('hasMember.*.'),
            $this->getReferenceRules('derivedFrom.*.'),
            $this->getCodeableConceptRules('component.*.code.'),
            $this->getQuantityRules('component.*.valueQuantity.'),
            $this->getCodeableConceptRules('component.*.valueCodeableConcept.'),
            $this->getRangeRules('component.*.valueRange.'),
            $this->getRatioRules('component.*.valueRatio.'),
            $this->getSampledDataRules('component.*.valueSampledData.'),
            $this->getPeriodRules('component.*.valuePeriod.'),
            $this->getCodeableConceptRules('component.*.dataAbsentReason.'),
            $this->getCodeableConceptRules('component.*.interpretation.*.'),
            $this->getSimpleQuantityRules('component.*.referenceRange.*.low.'),
            $this->getSimpleQuantityRules('component.*.referenceRange.*.high.'),
            $this->getCodeableConceptRules('component.*.referenceRange.*.type.'),
            $this->getCodeableConceptRules('component.*.referenceRange.*.appliesTo.'),
            $this->getRangeRules('component.*.referenceRange.*.age.'),
        );
    }
}
