<?php

namespace App;

class Constants
{
    public const NAME_USE_SYSTEM = 'http://hl7.org/fhir/name-use';
    public const NAME_USE_CODE = ['usual', 'official', 'temp', 'nickname', 'anonymous', 'old', 'maiden'];
    public const NAME_USE_DISPLAY = ['usual' => 'Usual', 'official' => 'Official', 'temp' => 'Temp', 'nickname' => 'Nickname', 'anonymous' => 'Anonymous', 'old' => 'Old', 'maiden' => 'Name changed for Marriage'];

    public const IDENTIFIER_USE = ['usual', 'official', 'temp', 'secondary', 'old'];
    public const IDENTIFIER_USE_DISPLAY = [
        'usual' => 'Identifier yang direkomendasikan digunakan untuk interaksi dunia nyata',
        'official' => 'Identifier yang dianggap paling terpercaya. Terkadang juga dikenal sebagai "primer" dan "utama". Penentuan "resmi" bersifat subyektif dan panduan implementasi seringkali memberikan panduan tambahan untuk digunakan.',
        'temp' => 'Identifier sementara',
        'secondary' => 'Identifier yang ditugaskan dalam penggunaan sekunder ini berfungsi untuk mengidentifikasi objek dalam konteks relatif, tetapi tidak dapat secara konsisten ditugaskan ke objek yang sama lagi dalam konteks yang berbeda.',
        'old' => 'Id identifier sudah dianggap tidak valid, tetapi masih memungkinkan relevan untuk kebutuhan pencarian.'
    ];
    public const NAKES_SYSTEM = "https://fhir.kemkes.go.id/id/nakes-id";
    public const NIK_SYSTEM = "https://fhir.kemkes.go.id/id/nik";

    public const TELECOM_SYSTEM_SYSTEM = 'http://hl7.org/fhir/contact-point-system';
    public const TELECOM_SYSTEM_CODE = ['phone', 'fax', 'email', 'pager', 'url', 'sms', 'other'];
    public const TELECOM_SYSTEM_DISPLAY = ['phone' => 'Phone', 'fax' => 'Fax', 'email' => 'Email', 'pager' => 'Pager', 'url' => 'URL', 'sms' => 'SMS', 'other' => 'Other'];
    public const TELECOM_SYSTEM_DEFINITION = ["phone" => "The value is a telephone number used for voice calls. Use of full international numbers starting with + is recommended to enable automatic dialing support but not required.", "fax" => "The value is a fax machine. Use of full international numbers starting with + is recommended to enable automatic dialing support but not required.", "email" => "The value is an email address.", "pager" => "The value is a pager number. These may be local pager numbers that are only usable on a particular pager system.", "url" => "A contact that is not a phone, fax, pager or email address and is expressed as a URL. This is intended for various institutional or personal contacts including web sites, blogs, Skype, Twitter, Facebook, etc. Do not use for email addresses.", "sms" => "A contact that can be used for sending an sms message (e.g. mobile phones, some landlines).", "other" => 'A contact that is not a phone, fax, page or email address and is not expressible as a URL. E.g. Internal mail address. This SHOULD NOT be used for contacts that are expressible as a URL (e.g. Skype, Twitter, Facebook, etc.) Extensions may be used to distinguish "other" contact types.'];

    public const TELECOM_USE_SYSTEM = 'http://hl7.org/fhir/contact-point-use';
    public const TELECOM_USE_CODE = ['home', 'work', 'temp', 'old', 'mobile'];
    public const TELECOM_USE_DISPLAY = ['home' => 'Home', 'work' => 'Work', 'temp' => 'Temp', 'old' => 'Old', 'mobile' => 'Mobile'];
    public const TELECOM_USE_DEFINITION = ["home" => "A communication contact point at a home; attempted contacts for business purposes might intrude privacy and chances are one will contact family or other household members instead of the person one wishes to call. Typically used with urgent cases, or if no other contacts are available.", "work" => "An office contact point. First choice for business related contacts during business hours.", "temp" => "A temporary contact point. The period can provide more detailed information.", "old" => "This contact point is no longer in use (or was never correct, but retained for records).", "mobile" => "A telecommunication device that moves and stays with its owner. May have characteristics of all other use codes, suitable for urgent matters, not the first choice for routine business."];

    public const ADDRESS_USE_SYSTEM = 'http://hl7.org/fhir/address-use';
    public const ADDRESS_USE_CODE = ['home', 'work', 'temp', 'old', 'billing'];
    public const ADDRESS_USE_DISPLAY = ['home' => 'Home', 'work' => 'Work', 'temp' => 'Temporary', 'old' => 'Old / Incorrect', 'billing' => 'Billing'];
    public const ADDRESS_USE_DEFINITION = ["home" => "A communication address at a home.", "work" => "An office address. First choice for business related contacts during business hours.", "temp" => "A temporary address. The period can provide more detailed information.", "old" => "This address is no longer in use (or was never correct but retained for records).", "billing" => "An address to be used to send bills, invoices, receipts etc."];

    public const ADDRESS_TYPE_SYSTEM = 'http://hl7.org/fhir/address-type';
    public const ADDRESS_TYPE_CODE = ['postal', 'physical', 'both'];
    public const ADDRESS_TYPE_DISPLAY = ['postal' => 'Alamat surat', 'physical' => 'Alamat fisik yang dapat dikunjungi', 'both' => 'Alamat yang bersifat fisik dan surat'];

    public const GENDER = ['male', 'female', 'other', 'unknown'];
    public const COMPARATOR = ['<', '<=', '>=', '>'];
    public const PERIOD_UNIT = ['s', 'min', 'h', 'd', 'wk', 'mo', 'a'];
    public const DAYS_OF_WEEK = ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'];

    public const TIMING_EVENT_SYSTEM = 'http://terminology.hl7.org/CodeSystem/v3-TimingEvent';
    public const TIMING_EVENT_CODE = ['AC', 'ACD', 'ACM', 'ACV', 'C', 'CD', 'CM', 'CV', 'HS', 'IC', 'ICD', 'ICM', 'ICV', 'PC', 'PCD', 'PCM', 'PCV', 'WAKE'];
    public const TIMING_EVENT_DISPLAY = ['AC' => 'AC', 'ACD' => 'ACD', 'ACM' => 'ACM', 'ACV' => 'ACV', 'C' => 'C', 'CD' => 'CD', 'CM' => 'CM', 'CV' => 'CV', 'HS' => 'HS', 'IC' => 'IC', 'ICD' => 'ICD', 'ICM' => 'ICM', 'ICV' => 'ICV', 'PC' => 'PC', 'PCD' => 'PCD', 'PCM' => 'PCM', 'PCV' => 'PCV', 'WAKE' => 'WAKE'];
    public const TIMING_EVENT_DEFINITION = ["AC" => "before meal (from lat. ante cibus)", "ACD" => "before lunch (from lat. ante cibus diurnus)", "ACM" => "before breakfast (from lat. ante cibus matutinus)", "ACV" => "before dinner (from lat. ante cibus vespertinus)", "C" => "Description: meal (from lat. ante cibus)", "CD" => "Description: lunch (from lat. cibus diurnus)", "CM" => "Description: breakfast (from lat. cibus matutinus)", "CV" => "Description: dinner (from lat. cibus vespertinus)", "HS" => "Description: Prior to beginning a regular period of extended sleep (this would exclude naps). Note that this might occur at different times of day depending on a person's regular sleep schedule.", "IC" => "between meals (from lat. inter cibus)", "ICD" => "between lunch and dinner", "ICM" => "between breakfast and lunch", "ICV" => "between dinner and the hour of sleep", "PC" => "after meal (from lat. post cibus)", "PCD" => "after lunch (from lat. post cibus diurnus)", "PCM" => "after breakfast (from lat. post cibus matutinus)", "PCV" => "after dinner (from lat. post cibus vespertinus)", "WAKE" => "Description: Upon waking up from a regular period of sleep, in order to start regular activities (this would exclude waking up from a nap or temporarily waking up during a period of sleep) Usage Notes: e.g. Take pulse rate on waking in management of thyrotoxicosis. Take BP on waking in management of hypertension Take basal body temperature on waking in establishing date of ovulation"];

    public const TIMING_ABBREVIATION_SYSTEM = 'http://hl7.org/fhir/ValueSet/timing-abbreviation';
    public const TIMING_ABBREVIATION_CODE = ['BID', 'TID', 'QID', 'AM', 'PM', 'QD', 'QOD', 'Q1H', 'Q2H', 'Q3H', 'Q4H', 'Q6H', 'Q8H', 'BED', 'WK', 'MO'];
    public const TIMING_ABBREVIATION_DISPLAY = ['BID' => 'BID', 'TID' => 'TID', 'QID' => 'QID', 'AM' => 'AM', 'PM' => 'PM', 'QD' => 'QD', 'QOD' => 'QOD', 'Q1H' => 'every hour', 'Q2H' => 'every 2 hours', 'Q3H' => 'every 3 hours', 'Q4H' => 'Q4H', 'Q6H' => 'Q6H', 'Q8H' => 'every 8 hours', 'BED' => 'at bedtime', 'WK' => 'weekly', 'MO' => 'monthly'];

    public const TIMING_REPEAT_WHEN_SYSTEM = ['MORN' => 'http://hl7.org/fhir/event-timing', 'MORN.early' => 'http://hl7.org/fhir/event-timing', 'MORN.late' => 'http://hl7.org/fhir/event-timing', 'NOON' => 'http://hl7.org/fhir/event-timing', 'AFT' => 'http://hl7.org/fhir/event-timing', 'AFT.early' => 'http://hl7.org/fhir/event-timing', 'AFT.late' => 'http://hl7.org/fhir/event-timing', 'EVE' => 'http://hl7.org/fhir/event-timing', 'EVE.early' => 'http://hl7.org/fhir/event-timing', 'EVE.late' => 'http://hl7.org/fhir/event-timing', 'NIGHT' => 'http://hl7.org/fhir/event-timing', 'PHS' => 'http://hl7.org/fhir/event-timing', 'HS' => 'http://terminology.hl7.org/CodeSystem/v3-TimingEvent', 'WAKE' => 'http://terminology.hl7.org/CodeSystem/v3-TimingEvent', 'C' => 'http://terminology.hl7.org/CodeSystem/v3-TimingEvent', 'CM' => 'http://terminology.hl7.org/CodeSystem/v3-TimingEvent', 'CD' => 'http://terminology.hl7.org/CodeSystem/v3-TimingEvent', 'CV' => 'http://terminology.hl7.org/CodeSystem/v3-TimingEvent', 'AC' => 'http://terminology.hl7.org/CodeSystem/v3-TimingEvent', 'ACM' => 'http://terminology.hl7.org/CodeSystem/v3-TimingEvent', 'ACD' => 'http://terminology.hl7.org/CodeSystem/v3-TimingEvent', 'ACV' => 'http://terminology.hl7.org/CodeSystem/v3-TimingEvent', 'PC' => 'http://terminology.hl7.org/CodeSystem/v3-TimingEvent', 'PCM' => 'http://terminology.hl7.org/CodeSystem/v3-TimingEvent', 'PCD' => 'http://terminology.hl7.org/CodeSystem/v3-TimingEvent', 'PCV' => 'http://terminology.hl7.org/CodeSystem/v3-TimingEvent'];
    public const TIMING_REPEAT_WHEN_CODE = ['MORN', 'MORN.early', 'MORN.late', 'NOON', 'AFT', 'AFT.early', 'AFT.late', 'EVE', 'EVE.early', 'EVE.late', 'NIGHT', 'PHS', 'HS', 'WAKE', 'C', 'CM', 'CD', 'CV', 'AC', 'ACM', 'ACD', 'ACV', 'PC', 'PCM', 'PCD', 'PCV'];
    public const TIMING_REPEAT_WHEN_DISPLAY = ["MORN" => "Morning", "MORN.early" => "Early Morning", "MORN.late" => "Late Morning", "NOON" => "Noon", "AFT" => "Afternoon", "AFT.early" => "Early Afternoon", "AFT.late" => "Late Afternoon", "EVE" => "Evening", "EVE.early" => "Early Evening", "EVE.late" => "Late Evening", "NIGHT" => "Night", "PHS" => "After Sleep", "HS" => "HS", "WAKE" => "WAKE", "C" => "C", "CM" => "CM", "CD" => "CD", "CV" => "CV", "AC" => "AC", "ACM" => "ACM", "ACD" => "ACD", "ACV" => "ACV", "PC" => "PC", "PCM" => "PCM", "PCD" => "PCD", "PCV" => "PCV"];
    public const TIMING_REPEAT_WHEN_DEFINITION = ["MORN" => "Pagi hari", "MORN.early" => "Early Morning", "MORN.late" => "Late Morning", "NOON" => "Sekitar pukul 12.00", "AFT" => "Sore hari", "AFT.early" => "Early Afternoon", "AFT.late" => "Late Afternoon", "EVE" => "Malam hari", "EVE.early" => "Early Evening", "EVE.late" => "Late Evening", "NIGHT" => "Malam hari", "PHS" => "Setelah tidur", "HS" => "Sebelum tidur", "WAKE" => "Setelah bangun tidur", "C" => "Saat makan", "CM" => "Saat sarapan", "CD" => "Saat makan siang", "CV" => "Saat makan malam", "AC" => "Sebelum makan", "ACM" => "Sebelum sarapan", "ACD" => "Sebelum makan siang", "ACV" => "Sebelum makan malam", "PC" => "Setelah makan", "PCM" => "Setelah sarapan", "PCD" => "Setelah makan siang", "PCV" => "Setelah makan malam"];

    public const TIMING_CODE_SYSTEM = 'http://terminology.hl7.org/3.1.0/CodeSystem-v3-GTSAbbreviation.html';
    public const TIMING_CODE_CODE = ['BID', 'TID', 'QID', 'AM', 'PM', 'QD', 'QOD', 'Q1H', 'Q2H', 'Q3H', 'Q4H', 'Q6H', 'Q8H', 'BED', 'WK', 'MO'];
    public const TIMING_CODE_DISPLAY = ["BID" => "BID", "TID" => "TID", "QID" => "QID", "AM" => "AM", "PM" => "PM", "QD" => "QD", "QOD" => "QOD", "Q1H" => "Every hour", "Q2H" => "Every 2 hours", "Q3H" => "Every 3 hours", "Q4H" => "Q4H", "Q6H" => "Q6H", "Q8H" => "every 8 hours", "BED" => "at bedtime", "WK" => "weekly", "MO" => "monthly"];
    public const TIMING_CODE_DEFINITION = ["BID" => "2 kali sehari berdasarkan waktu di fasilitas kesehatan.", "TID" => "3 kali sehari berdasarkan waktu yang ditentukan oleh fasilitas kesehatan.", "QID" => "4 kali sehari berdasarkan waktu yang ditentukan oleh fasilitas kesehatan.", "AM" => "Setiap pagi berdasarkan waktu yang ditentukan oleh fasilitas kesehatan.", "PM" => "Setiap siang berdasarkan waktu yang ditentukan oleh fasilitas kesehatan.", "QD" => "Setiap hari berdasarkan waktu yang ditentukan oleh fasilitas kesehatan.", "QOD" => "Setiap hari lain berdasarkan waktu yang ditentukan oleh fasilitas kesehatan.", "Q1H" => "Setiap jam berdasarkan waktu yang ditentukan oleh fasilitas kesehatan.", "Q2H" => "Setiap 2 jam berdasarkan waktu yang ditentukan oleh fasilitas kesehatan.", "Q3H" => "Setiap 3 jam berdasarkan waktu yang ditentukan oleh fasilitas kesehatan.", "Q4H" => "Setiap 4 jam berdasarkan waktu yang ditentukan oleh fasilitas kesehatan.", "Q6H" => "Setiap 6 jam berdasarkan waktu yang ditentukan oleh fasilitas kesehatan.", "Q8H" => "Setiap 8 jam berdasarkan waktu yang ditentukan oleh fasilitas kesehatan.", "BED" => "Waktu tidur (berdasarkan waktu yang ditentukan oleh fasilitas kesehatan).", "WK" => "Seminggu sekali berdasarkan waktu yang ditentukan oleh fasilitas kesehatan.", "MO" => "Sebulan sekali berdasarkan waktu yang ditentukan oleh fasilitas kesehatan."];

    public const DOSAGE_ROUTE_SYSTEM = 'http://www.whocc.no/atc';
    public const DOSAGE_ROUTE_CODE = ['implant', 'Inhal', 'Instill', 'N', 'O', 'P', 'R', 'SL', 'TD', 'V', 'Inhal.powder', 'Inhal.aerosol', 'Inhal.solution', 'urethral', 'TD patch', 'intravesical', 'Instill.solution', 'lamella', 'oral aerosol', 's.c. implant', 'ocular', 'otic', 'cutaneous', 'inj.subcutaneous', 'inj.intramuscular', 'inj.intravenous', 'inj.intrathecal', 'Chewing Gum', 'ointment', 'stomatologic'];
    public const DOSAGE_ROUTE_DISPLAY = ["implant" => "Implant", "Inhal" => "Inhalation", "Instill" => "Instillation", "N" => "Nasal", "O" => "Oral", "P" => "Parenteral", "R" => "Rectal", "SL" => "Sublingual/Buccal/Oro mucosal", "TD" => "Transdermal", "V" => "Vaginal", "Inhal.powder" => "Inhalation Powder", "Inhal.aerosol" => "Inhalation Aerosol", "Inhal.solution" => "Inhalation Solution", "urethral" => "Urethral", "TD patch" => "Transdermal Patch", "intravesical" => "Intravesical", "Instill.solution" => "Instillation Solution", "lamella" => "Lamella", "oral aerosol" => "Oral Aerosol", "s.c. implant" => "S.C. Implant", "ocular" => "Ocular", "otic" => "Otic", "cutaneous" => "Cutaneous", "inj.subcutaneous" => "Injection Subcutaneous", "inj.intramuscular" => "Injection Intramuscular", "inj.intravenous" => "Injection Intravenous", "inj.intrathecal" => "Injection Intrathecal", "Chewing Gum" => "Chewing Gum", "ointment" => "Ointment", "stomatologic" => "stomatologic"];
    public const DOSAGE_ROUTE_DEFINITION = ["implant" => "Implant", "Inhal" => "Inhalasi (dihirup)", "Instill" => "Instillation", "N" => "Nasal", "O" => "Oral", "P" => "Parenteral", "R" => "Rektum", "SL" => "Sublingual (di bawah lidah) / bukal (diantara gusi & pipi)", "TD" => "Transdermal", "V" => "Vagina", "Inhal.powder" => "Bubuk inhalasi", "Inhal.aerosol" => "Aerosol inhalasi", "Inhal.solution" => "Larutan inhalasi", "urethral" => "Uretra", "TD patch" => "Transdermal patch", "intravesical" => "Intravesical", "Instill.solution" => "Instillation solution", "lamella" => "Ophtalmic", "oral aerosol" => "Aerosol oral", "s.c. implant" => "S.C. implant", "ocular" => "Ocular (mata)", "otic" => "Otic (telinga)", "cutaneous" => "Kutanea (kulit)", "inj.subcutaneous" => "Subkutan Injeksi (di bawah kulit)", "inj.intramuscular" => "Intramuskular Injeksi (di dalam otot)", "inj.intravenous" => "Intravena Injeksi (ke pembuluh darah)", "inj.intrathecal" => "Intratekal Injeksi (sekitar sumsum tulang belakang)", "Chewing Gum" => "Dikunyah", "ointment" => "Topikal", "stomatologic" => "stomatologic"];

    public const DOSERATE_TYPE_SYSTEM = 'https://hl7.org/FHIR/codesystem-dose-rate-type.html';
    public const DOSERATE_TYPE_CODE = ['calculated', 'ordered'];
    public const DOSERATE_TYPE_DISPLAY = ["calculated" => "Calculated", "ordered" => "Ordered"];
    public const DOSERATE_TYPE_DEFINITION = ["calculated" => "Dosis yang ditentukan dihitung oleh sistem atau yang meresepkan obat", "ordered" => "Dosis yang ditentukan seperti yang diminta oleh peresep obat"];
}
